Resources:
  MealsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${self:service}-${self:provider.stage}-MealsQueue
      VisibilityTimeout: 130
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        maxReceiveCount: 2
        deadLetterTargetArn: !GetAtt MealsDLQ.Arn

  MealsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${self:service}-${self:provider.stage}-MealsDLQueue
      MessageRetentionPeriod: 1209600 # 14 days

  MealsDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${self:service}-${self:provider.stage}-MealsDLQAlarm
      AlarmDescription: "Alarm when there are messages in the Meals DLQ"
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !GetAtt MealsDLQ.QueueName
      Statistic: Average
      Period: 60 # 5 minutes
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref DLQAlarmsTopic
